### ISSUE TITLE
[BUG] OpenSearch Dashboards distribution build fails on security-analytics-dashboards for windows platform

### ISSUE THREAD

**Issue by zelinh** [opensearch-project/security-analytics-dashboards-plugin#546]
**What is the bug?**
OpenSearch Dashboards distribution build fails on security-analytics-dashboards for windows platform
More context:
```
node ../../scripts/plugin_helpers build --opensearch-dashboards-version=2.7.0

 info Loaded config file from [C:\Users\Administrator\AppData\Local\Temp\tmpe_os70fh\OpenSearch-Dashboards\plugins\securityAnalyticsDashboards\.opensearch_dashboards-plugin-helpers.json]

 info deleting the build and target directories

 info running @osd/optimizer

 â”‚ info initialized, 0 bundles cached

 â”‚ info starting worker [1 bundle]

 â”‚ERROR webpack compile errors

     â”‚ERROR [securityAnalyticsDashboards] build

         â”‚ERROR Optimizations failure.

         â”‚         343 modules

         â”‚          

         â”‚          ERROR in ./public/store/CorrelationsStore.ts

         â”‚          Module build failed (from C:/Users/Administrator/AppData/Local/Temp/tmpe_os70fh/OpenSearch-Dashboards/node_modules/babel-loader/lib/index.js):

         â”‚          Error: C:\Users\Administrator\AppData\Local\Temp\tmpe_os70fh\OpenSearch-Dashboards\plugins\securityAnalyticsDashboards\public\store\CorrelationsStore.ts: Couldn't find a Program

         â”‚              at Scope.getProgramParent (C:\Users\ADMINI~1\AppData\Local\Temp\tmpe_os70fh\OpenSearch-Dashboards\node_modules\@babel\traverse\lib\scope\index.js:864:11)

         â”‚              at Scope.crawl (C:\Users\ADMINI~1\AppData\Local\Temp\tmpe_os70fh\OpenSearch-Dashboards\node_modules\@babel\traverse\lib\scope\index.js:769:32)

         â”‚              at Scope.init (C:\Users\ADMINI~1\AppData\Local\Temp\tmpe_os70fh\OpenSearch-Dashboards\node_modules\@babel\traverse\lib\scope\index.js:758:12)

         â”‚              at NodePath.setScope (C:\Users\ADMINI~1\AppData\Local\Temp\tmpe_os70fh\OpenSearch-Dashboards\node_modules\@babel\traverse\lib\path\context.js:142:30)

         â”‚              at NodePath.setContext (C:\Users\ADMINI~1\AppData\Local\Temp\tmpe_os70fh\OpenSearch-Dashboards\node_modules\@babel\traverse\lib\path\context.js:158:8)

         â”‚              at NodePath.popContext (C:\Users\ADMINI~1\AppData\Local\Temp\tmpe_os70fh\OpenSearch-Dashboards\node_modules\@babel\traverse\lib\path\context.js:218:10)

         â”‚              at TraversalContext.visitQueue (C:\Users\ADMINI~1\AppData\Local\Temp\tmpe_os70fh\OpenSearch-Dashboards\node_modules\@babel\traverse\lib\context.js:117:12)

         â”‚              at TraversalContext.visitMultiple (C:\Users\ADMINI~1\AppData\Local\Temp\tmpe_os70fh\OpenSearch-Dashboards\node_modules\@babel\traverse\lib\context.js:72:17)

         â”‚              at TraversalContext.visit (C:\Users\ADMINI~1\AppData\Local\Temp\tmpe_os70fh\OpenSearch-Dashboards\node_modules\@babel\traverse\lib\context.js:129:19)

         â”‚              at traverseNode (C:\Users\ADMINI~1\AppData\Local\Temp\tmpe_os70fh\OpenSearch-Dashboards\node_modules\@babel\traverse\lib\traverse-node.js:24:17)

         â”‚           @ ./public/store/DataStore.ts 11:0-56 25:36-53

         â”‚           @ ./public/security_analytics_app.tsx

         â”‚           @ ./public/plugin.ts

         â”‚           @ ./public/index.ts

         â”‚           @ C:/Users/ADMINI~1/AppData/Local/Temp/tmpe_os70fh/OpenSearch-Dashboards/packages/osd-optimizer/target/worker/entry_point_creator.js

 â”‚ERROR webpack issue

error Command failed with exit code 1.

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

2023-04-19 21:55:52 ERROR    Error building securityAnalyticsDashboards, retry with: ./build.sh manifests/2.7.0/opensearch-dashboards-2.7.0.yml --component securityAnalyticsDashboards
```
This is the jenkins build job link. https://build.ci.opensearch.org/blue/organizations/jenkins/distribution-build-opensearch-dashboards/detail/distribution-build-opensearch-dashboards/6085/pipeline

**Comment by amsiglan** [comment]
Fixed by #539
